console.log('avinash set')
let s=new Set()
s.add(12)
s.add(12)
s.add(39)
s.add(3)
s.add(9)
console.log(s)
console.log(s.size)
console.log(s.has(4))
s.delete(9) 
console.log(s)

let s2=Symbol('avinash sharma ')
let s1=Symbol('avinash sharma ')
console.log(s2,s1)
console.log(s2==s1)
console.log(s2 ==s1)
